### ISSUE TITLE
Dudas sobre objetos JSON y Schema

### ISSUE THREAD

**Issue by OscarPozoFdez** [ULL-ESIT-INF-DSI-2021/ull-esit-inf-dsi-20-21-prct11-menu-api-grupo-p#1]
Buenas tardes, profes. @esegredo  @amarrerod @lgforte 

Tenemos una duda sobre qué tipo de datos en formato JSON enviar cuando queremos crear nuevas entradas en la base de datos con Mongoose.

1- Cuando creamos un objeto plato o menu y este tiene dentro como atributos una serie de objetos ingredientes o platos ¿Basta con indicarles estos ingredientes en formato string? ¿O obligatoriamente tiene que tener un objeto alimento o plato (con todos sus valores)?

2- Otro ejemplo relacionado, ¿El precio del menu, lo obtenemos sumando el precio de platos y alimentos? ¿O simplemente le asignamos el precio a los menús bajo nuestro criterio?

3- Y la última duda es sobre los macronutrientes, que están estructurados como un 'type', ¿también debemos guardarlos en el mismo formato o nos vale un string?

Básicamente las 3 preguntas son casi la misma: ¿podemos incluir estructrras de datos más complejas en la base de datos (objetos, types, etc) o basta con usar strings con la información introducida a mano?

Un saludo y gracias por adelantado.

**Comment by esegredo** [comment]
Hola @MisterDesgraciao , buenos días.

1. Debería ser un objeto y no un string.
2. El precio debe calcularse, al igual que la información nutricional del plato, a partir de los precios y nutrientes de los ingredientes (es hacer lo mismo que en la primera práctica grupal).
3. Ídem que respuestas anteriores.

En resumen, deben almacenar estructuras más complejas en la BBDD. Para ello existe JSON :-)
